-- -----------------------------------------------------
-- CREACION DE LA BASE DE DATOS
-- -----------------------------------------------------

DROP SCHEMA MYDB;
CREATE DATABASE MYDB;
USE MYDB;
-- DROP SCHEMA MYDB;

-- -----------------------------------------------------
-- CREACION DE LAS TABLAS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `CIUDADES` (
  `ID_CIUDAD` INT NOT NULL AUTO_INCREMENT,
  `CIUDAD` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_CIUDAD`))
ENGINE = InnoDB;

-- CREATE UNIQUE INDEX CIUDADES
-- ON VEHICULOS (ID_CIUDAD);

CREATE TABLE IF NOT EXISTS `SUCURSALES` (
  `ID_SUCURSAL` INT NOT NULL AUTO_INCREMENT,
  `DIRECCION` VARCHAR(100) NOT NULL,
  `TELEFONO_FIJO` VARCHAR(45) NOT NULL,
  `CELULAR` VARCHAR(45) NOT NULL,
  `CIUDADES_ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_SUCURSAL`),
  INDEX `fk_SUCURSALES_CIUDADES1_idx` (`CIUDADES_ID_CIUDAD` ASC) VISIBLE,
  CONSTRAINT `fk_SUCURSALES_CIUDADES1`
    FOREIGN KEY (`CIUDADES_ID_CIUDAD`)
    REFERENCES `CIUDADES` (`ID_CIUDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE UNIQUE INDEX SUCURSALES_ID
-- ON VEHICULOS (ID_SUCURSAL);

CREATE TABLE IF NOT EXISTS `VEHICULOS` (
  `ID_VEHICULO` INT NOT NULL AUTO_INCREMENT,
  `PLACA` VARCHAR(10) NOT NULL,
  `REFERENCIA` VARCHAR(100) NOT NULL,
  `TIPO` VARCHAR(100) NOT NULL, -- SE DEFINIERON TRES TIPOS DE AUTOMOVILES, DEPORTIVOS, SEDAN Y CROSSOVER
  `MODELO` VARCHAR(10) NOT NULL,
  `PUERTAS` VARCHAR(10) NOT NULL,
  `CAPACIDAD` INT NOT NULL,
  `SUNROOF` BOOLEAN NOT NULL,
  `MOTOR` VARCHAR(45) NOT NULL,
  `VALOR_DIA` INT NOT NULL,
  `ESTADO_ALQUILADO` BOOLEAN NOT NULL,
  `SUCURSALES_ID_SUCURSAL` INT NOT NULL,
  PRIMARY KEY (`ID_VEHICULO`),
  INDEX `fk_VEHICULOS_SUCURSALES_idx` (`SUCURSALES_ID_SUCURSAL` ASC) VISIBLE,
  CONSTRAINT `fk_VEHICULOS_SUCURSALES`
    FOREIGN KEY (`SUCURSALES_ID_SUCURSAL`)
    REFERENCES `SUCURSALES` (`ID_SUCURSAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE UNIQUE INDEX VEHICULOS_ID
-- ON VEHICULOS (ID_VEHICULO);

CREATE TABLE IF NOT EXISTS `EMPLEADOS` (
  `ID_EMPLEADO` INT NOT NULL AUTO_INCREMENT,
  `CEDULA` VARCHAR(45) NOT NULL,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `DIRECCION` VARCHAR(100) NOT NULL,
  `CELULAR` VARCHAR(45) NULL,
  `CORREO_ELECTRONICO` VARCHAR(100) NOT NULL,
  `CONTRASENA` VARCHAR(45) NOT NULL,
  `SUCURSALES_ID_SUCURSAL` INT NOT NULL,
  `CIUDADES_ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_EMPLEADO`),
  INDEX `fk_EMPLEADOS_SUCURSALES1_idx` (`SUCURSALES_ID_SUCURSAL` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADOS_SUCURSALES1`
    FOREIGN KEY (`SUCURSALES_ID_SUCURSAL`)
    REFERENCES `SUCURSALES` (`ID_SUCURSAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADOS_CIUDADES1`
    FOREIGN KEY (`CIUDADES_ID_CIUDAD`)
    REFERENCES `CIUDADES` (`ID_CIUDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE UNIQUE INDEX EMPLEADOS_ID
-- ON EMPLEADOS (ID_EMPLEADO);

CREATE TABLE IF NOT EXISTS `CLIENTES` (
  `ID_CLIENTES` INT NOT NULL AUTO_INCREMENT,
  `CEDULA` VARCHAR(45) NOT NULL,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `DIRECCION` VARCHAR(100) NOT NULL,
  `CELULAR` VARCHAR(45) NULL,
  `CORREO_ELECTRONICO` VARCHAR(100) NOT NULL,
  `CONTRASENA` VARCHAR(45) NOT NULL,
  `CIUDADES_ID_CIUDAD` INT NOT NULL,
  PRIMARY KEY (`ID_CLIENTES`),
  INDEX `fk_CLIENTES_CIUDADES1_idx` (`CIUDADES_ID_CIUDAD` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_CIUDADES1`
    FOREIGN KEY (`CIUDADES_ID_CIUDAD`)
    REFERENCES `mydb`.`CIUDADES` (`ID_CIUDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- CREATE UNIQUE INDEX CLIENTES_ID
-- ON CLIENTES (ID_CLIENTES);

CREATE TABLE IF NOT EXISTS `ALQUILERES` (
  `ID_ALQUILER` INT NOT NULL AUTO_INCREMENT,
  `ID_SUCURSAL_SALIDA` INT NOT NULL,
  `FECHA_SALIDA` DATETIME NOT NULL,
  `ID_SUCURSAL_LLEGADA` INT NOT NULL,
  `FECHA_LLEGADA` DATETIME NOT NULL,
  `VALOR_SEMANA` INT NOT NULL,
  `VALOR_DIA` INT NOT NULL,
  `PORCENTAJE_DESCUENTO` INT NOT NULL, -- EXPRESADO EN UNA ESCALA DEL 0 AL 100
  `VALOR_COTIIZADO` INT NOT NULL,
  `VALOR_PAGADO` INT NOT NULL,
  `VEHICULOS_ID_VEHICULO` INT NOT NULL,
  `EMPLEADOS_ID_EMPLEADO` INT NOT NULL,
  `CLIENTES_ID_CLIENTES` INT NOT NULL,
  `ESTADO_ENTREGADO` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID_ALQUILER`),
  INDEX `fk_ALQUILERES_VEHICULOS1_idx` (`VEHICULOS_ID_VEHICULO` ASC) VISIBLE,
  INDEX `fk_ALQUILERES_EMPLEADOS1_idx` (`EMPLEADOS_ID_EMPLEADO` ASC) VISIBLE,
  INDEX `fk_ALQUILERES_CLIENTES1_idx` (`CLIENTES_ID_CLIENTES` ASC) VISIBLE,
  CONSTRAINT `fk_ALQUILERES_VEHICULOS1`
    FOREIGN KEY (`VEHICULOS_ID_VEHICULO`)
    REFERENCES `VEHICULOS` (`ID_VEHICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALQUILERES_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_ID_EMPLEADO`)
    REFERENCES `EMPLEADOS` (`ID_EMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALQUILERES_CLIENTES1`
    FOREIGN KEY (`CLIENTES_ID_CLIENTES`)
    REFERENCES `CLIENTES` (`ID_CLIENTES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = INNODB;

-- CREATE UNIQUE INDEX ALQUILERES_ID
-- ON ALQUILERES (ID_ALQUILER);

-- -----------------------------------------------------
-- DESARROLLO DEL REGISTRO DE CIUDADES, SURCUSALES Y VEHICULOS
-- -----------------------------------------------------

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_CIUDAD = 'Bucaramanga';
INSERT INTO CIUDADES(CIUDAD)
VALUES(@FIELD_CIUDAD);

SET @FIELD_CIUDAD = 'Piedecuesta';
INSERT INTO CIUDADES(CIUDAD)
VALUES(@FIELD_CIUDAD);

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_CIUDAD = 1; -- CIUDAD BUCARAMANGA
SET @FIELD_DIRECCION = 'Carrera 35 # 34-02';
SET @FIELD_TELEFONO_FIJO = '6650185';
SET @FIELD_CELULAR = '31045006099';

INSERT INTO SUCURSALES(DIRECCION, TELEFONO_FIJO, CELULAR, CIUDADES_ID_CIUDAD)
VALUES(@FIELD_DIRECCION, @FIELD_TELEFONO_FIJO, @FIELD_CELULAR, @FIELD_CIUDAD);
-- SELECT * FROM SUCURSALES;

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_PLACA = 'PIS-890';
SET @FIELD_REFERENCIA= 'Camioneta Mazda CX-5';
SET @FIELD_TIPO = 'Crossover';
SET @FIELD_MODELO = '2020';
SET @FIELD_PUERTAS = '4';
SET @FIELD_CAPACIDAD = '5';
SET @FIELD_SUNROOF = FALSE;
SET @FIELD_MOTOR = 'Motor a gasolina, 1800 caballos de fuerza';
SET @FIELD_VALOR_DIA = 87638;
SET @FIELD_ID_SUCURSAL = 1;

INSERT INTO VEHICULOS(PLACA, REFERENCIA, TIPO ,MODELO, PUERTAS, CAPACIDAD, SUNROOF, MOTOR, VALOR_DIA, SUCURSALES_ID_SUCURSAL, ESTADO_ALQUILADO)
VALUES(@FIELD_PLACA, @FIELD_REFERENCIA, @FIELD_TIPO ,@FIELD_MODELO, @FIELD_PUERTAS, @FIELD_CAPACIDAD, @FIELD_SUNROOF, @FIELD_MOTOR, @FIELD_VALOR_DIA, @FIELD_ID_SUCURSAL, FALSE);
-- SELECT * FROM VEHICULOS;

-- -----------------------------------------------------
-- DESARROLLO DEL REGISTRO DE EMPLEADOS Y CLIENTES
-- -----------------------------------------------------

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_CEDULA = '1105784468';
SET @FIELD_NOMBRES = 'Cristian Julian';
SET @FIELD_APELLIDOS = 'Muñoz Buenahora';
SET @FIELD_DIRECCION = 'Calle 5000 # 70-80 Avenida Madrid';
SET @FIELD_CELULAR = '39045686032';
SET @FIELD_CORREO_ELECTRONICO = 'cristian@gmail.com';
SET @FIELD_PASSWORD = 'estudianteBaseDeDatos2022*/';
SET @FIELD_CIUDAD = 1;

INSERT INTO CLIENTES(CEDULA, NOMBRES, APELLIDOS, DIRECCION, CELULAR, CORREO_ELECTRONICO, CONTRASENA, CIUDADES_ID_CIUDAD)
VALUES(@FIELD_CEDULA, @FIELD_NOMBRES, @FIELD_APELLIDOS, @FIELD_DIRECCION, @FIELD_CELULAR,@FIELD_CORREO_ELECTRONICO, @FIELD_PASSWORD, @FIELD_CIUDAD);
-- SELECT * FROM CLIENTES;

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_CEDULA = '91057400';
SET @FIELD_NOMBRES = 'Ernesto';
SET @FIELD_APELLIDOS = 'Muñoz Ballesteros';
SET @FIELD_DIRECCION = 'Calle 2 # 15-20';
SET @FIELD_CELULAR = '32079680032';
SET @FIELD_CORREO_ELECTRONICO = 'ernesto@gmail.com';
SET @FIELD_PASSWORD = 'emplErnesto2022*/';
SET @FIELD_ID_SUCURSAL = 1;
SET @FIELD_CIUDAD = 2;

INSERT INTO EMPLEADOS(CEDULA, NOMBRES, APELLIDOS, DIRECCION, CELULAR, CORREO_ELECTRONICO, CONTRASENA, SUCURSALES_ID_SUCURSAL, CIUDADES_ID_CIUDAD)
VALUES(@FIELD_CEDULA, @FIELD_NOMBRES, @FIELD_APELLIDOS, @FIELD_DIRECCION, @FIELD_CELULAR,@FIELD_CORREO_ELECTRONICO, @FIELD_PASSWORD, @FIELD_ID_SUCURSAL, @FIELD_CIUDAD);

-- SELECT * FROM EMPLEADOS;

-- -----------------------------------------------------
-- DESARROLLO DEL INICIO DE SESION DE EMPLEADOS Y CLIENTES
-- -----------------------------------------------------

SET @SQLEMPLEADOLOGIN = 'SELECT * FROM EMPLEADOS WHERE CORREO_ELECTRONICO=? AND CONTRASENA=?';

-- INFORMACION INGRESADA POR EL USUARIO

SET @LOGIN_CORREO_ELECTRONICO = 'ernesto@gmail.com';
SET @LOGIN_PASSWORD = 'emplErnesto2022*/';

PREPARE LOGIN FROM @SQLEMPLEADOLOGIN;
EXECUTE LOGIN USING @LOGIN_CORREO_ELECTRONICO, @LOGIN_PASSWORD;


SET @SQLCLIENTELOGIN = 'SELECT * FROM CLIENTES WHERE CORREO_ELECTRONICO=? AND CONTRASENA=?';

-- INFORMACION INGRESADA POR EL USUARIO

SET @LOGIN_CORREO_ELECTRONICO = 'cristian@gmail.com';
SET @LOGIN_PASSWORD = 'estudianteBaseDeDatos2022*/';

PREPARE LOGIN FROM @SQLCLIENTELOGIN;
EXECUTE LOGIN USING @LOGIN_CORREO_ELECTRONICO, @LOGIN_PASSWORD;

-- -----------------------------------------------------
-- CONSULTA DE DISPONIBILIDAD DE VEHÍCULOS PARA ALQUILER POR TIPO DE VEHÍCULO, RANGO DE PRECIOS DE ALQUILER Y FECHAS DE DISPONIBILIDAD
-- -----------------------------------------------------

SET @SQL_CONSULTA_VEHICULO_TIPO = 'SELECT * FROM VEHICULOS WHERE VEHICULOS.ESTADO_ALQUILADO != 1 AND VEHICULOS.TIPO=?';

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_TIPO_VEHICULO_CONSULTA = 'Deportivo';

PREPARE CONSULTA FROM @SQL_CONSULTA_VEHICULO_TIPO;
EXECUTE CONSULTA USING @FIELD_TIPO_VEHICULO_CONSULTA;

SET @SQL_CONSULTA_VEHICULO_PRECIO = 'SELECT * FROM VEHICULOS WHERE VEHICULOS.ESTADO_ALQUILADO != 1 AND VEHICULOS.VALOR_DIA>? AND VEHICULOS.VALOR_DIA<?';

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_PRECIO_MINIMO_CONSULTA = 70000;
SET @FIELD_PRECIO_MAXIMO_CONSULTA = 200000;

PREPARE CONSULTA FROM @SQL_CONSULTA_VEHICULO_PRECIO;
EXECUTE CONSULTA USING @FIELD_PRECIO_MINIMO_CONSULTA, @FIELD_PRECIO_MAXIMO_CONSULTA;


SET @SQL_CONSULTA_VEHICULO_FECHA = 'SELECT VEHICULOS.* FROM VEHICULOS WHERE ID_VEHICULO = ANY (SELECT VEHICULOS_ID_VEHICULO FROM ALQUILERES WHERE DATEDIFF(?,ALQUILERES.FECHA_LLEGADA)>0);';

SET @FIELD_FECHA_VEHICULO_CONSULTA = DATE_ADD(NOW(), INTERVAL 1 DAY);

PREPARE CONSULTA FROM @SQL_CONSULTA_VEHICULO_FECHA;
EXECUTE CONSULTA USING @FIELD_FECHA_VEHICULO_CONSULTA;

-- -----------------------------------------------------
-- ALQUILER DE VEHICULOS
-- -----------------------------------------------------

-- INFORMACION INGRESADA POR EL USUARIO

SET @FIELD_ID_SUCURSAL_SALIDA = 1;
SET @FIELD_FECHA_SALIDA = NOW();
SET @FIELD_ID_SUCURSAL_LLEGADA = 1; -- SE DEFINE INICIALMENTE UNA SEDE PARA LA ENTREGA DEL VEHICULO AL REALIZAR EL ALQUILER PERO ESTA PUEDE SER ACTUALIZADA MAS ADELANTE
SET @FIELD_DIAS_PRESTAMO = 20; -- ESTE CAMPO NO HACE PARTE DE LA TABLA ALQUILERES PERO SE DEBE SOLICITAR AL REALIZAR EL PROCESO DE ALQUILER
SET @FIELD_FECHA_LLEGADA = DATE_ADD(NOW(), INTERVAL @FIELD_DIAS_PRESTAMO DAY);
SET @FIELD_PORCENTAJE_DESCUENTO = 0;
SET @FIELD_VALOR_PAGADO = 0;
SET @FIELD_ID_VEHICULO = 1;
SET @FIELD_ID_EMPLEADO_ENCARGADO = 1;
SET @FIELD_ID_CLIENTE = 1;
SET @FIELD_ESTADO_ENTREGADO = FALSE;

CREATE TRIGGER ALQUILER_INSERTAR_VALOR BEFORE INSERT ON ALQUILERES FOR EACH ROW
    BEGIN
        SET @TEMP_ID_VEHICULO = NEW.VEHICULOS_ID_VEHICULO;
        SET @TEMP_VALUE = (SELECT VEHICULOS.VALOR_DIA FROM VEHICULOS WHERE VEHICULOS.ID_VEHICULO = @TEMP_ID_VEHICULO);
        SET @TEMP_DIAS_PRESTAMO = DATEDIFF(NEW.FECHA_LLEGADA, NEW.FECHA_SALIDA);
        SET NEW.VALOR_DIA = @TEMP_VALUE;
        SET NEW.VALOR_SEMANA = @TEMP_VALUE * 7;
        SET NEW.VALOR_COTIIZADO = @TEMP_VALUE * @TEMP_DIAS_PRESTAMO;
    END;

CREATE TRIGGER ALQUILER_CAMBIAR_ESTADO_VEHICULO BEFORE INSERT ON ALQUILERES FOR EACH ROW
    UPDATE VEHICULOS
    SET VEHICULOS.ESTADO_ALQUILADO = TRUE
    WHERE NEW.VEHICULOS_ID_VEHICULO = VEHICULOS.ID_VEHICULO;

CREATE TRIGGER ALQUILER_ACTUALIZAR_VALOR BEFORE UPDATE ON ALQUILERES FOR EACH ROW
    BEGIN
        IF DATEDIFF(NEW.FECHA_LLEGADA, NEW.FECHA_SALIDA) > DATEDIFF(OLD.FECHA_LLEGADA, OLD.FECHA_SALIDA) THEN
            SET NEW.VALOR_COTIIZADO = OLD.VALOR_COTIIZADO * 1.08;
        END IF;
    END;


INSERT INTO ALQUILERES(ID_SUCURSAL_SALIDA, FECHA_SALIDA, ID_SUCURSAL_LLEGADA, FECHA_LLEGADA, VALOR_SEMANA, VALOR_DIA, PORCENTAJE_DESCUENTO, VALOR_COTIIZADO, VALOR_PAGADO, VEHICULOS_ID_VEHICULO, EMPLEADOS_ID_EMPLEADO, CLIENTES_ID_CLIENTES, ESTADO_ENTREGADO)
VALUES(@FIELD_ID_SUCURSAL_SALIDA, @FIELD_FECHA_SALIDA , @FIELD_ID_SUCURSAL_LLEGADA, @FIELD_FECHA_LLEGADA , 0, 0, @FIELD_PORCENTAJE_DESCUENTO, 0, @FIELD_VALOR_PAGADO, @FIELD_ID_VEHICULO, @FIELD_ID_EMPLEADO_ENCARGADO, @FIELD_ID_CLIENTE, @FIELD_ESTADO_ENTREGADO);
-- SELECT * FROM ALQUILERES;


-- -----------------------------------------------------
-- CONSULTA HISTORIAL DE ALQUILERES
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `HISTORIAL_ALQUILERES` (
  `ID_ALQUILER_HISTORIAL` INT NOT NULL AUTO_INCREMENT,
  `ID_ALQUILER` INT NOT NULL,
  `ID_SUCURSAL_SALIDA` INT NOT NULL,
  `FECHA_SALIDA` DATETIME NOT NULL,
  `ID_SUCURSAL_LLEGADA` INT NOT NULL,
  `FECHA_LLEGADA` DATETIME NOT NULL,
  `VALOR_SEMANA` INT NOT NULL,
  `VALOR_DIA` INT NOT NULL,
  `PORCENTAJE_DESCUENTO` INT NOT NULL,
  `VALOR_COTIIZADO` INT NOT NULL,
  `VALOR_PAGADO` INT NOT NULL,
  `VEHICULOS_ID_VEHICULO` INT NOT NULL,
  `EMPLEADOS_ID_EMPLEADO` INT NOT NULL,
  `CLIENTES_ID_CLIENTES` INT NOT NULL,
  `ESTADO_ENTREGADO` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID_ALQUILER_HISTORIAL`))
ENGINE = INNODB;

CREATE UNIQUE INDEX HISTORIAL_ALQUILERES_ID
ON HISTORIAL_ALQUILERES (ID_ALQUILER_HISTORIAL);

CREATE TRIGGER ALQUILER_INSERTAR_HISTORIAL AFTER INSERT ON ALQUILERES FOR EACH ROW
    BEGIN
        INSERT INTO HISTORIAL_ALQUILERES(ID_ALQUILER, ID_SUCURSAL_SALIDA, FECHA_SALIDA, ID_SUCURSAL_LLEGADA, FECHA_LLEGADA, VALOR_SEMANA, VALOR_DIA, PORCENTAJE_DESCUENTO, VALOR_COTIIZADO, VALOR_PAGADO, VEHICULOS_ID_VEHICULO, EMPLEADOS_ID_EMPLEADO, CLIENTES_ID_CLIENTES, ESTADO_ENTREGADO)
            VALUES(NEW.ID_ALQUILER, NEW.ID_SUCURSAL_SALIDA, NEW.FECHA_SALIDA, NEW.ID_SUCURSAL_LLEGADA, NEW.FECHA_LLEGADA, NEW.VALOR_SEMANA, NEW.VALOR_DIA, NEW.PORCENTAJE_DESCUENTO, NEW.VALOR_COTIIZADO, NEW.VALOR_PAGADO, NEW.VEHICULOS_ID_VEHICULO, NEW.EMPLEADOS_ID_EMPLEADO, NEW.CLIENTES_ID_CLIENTES, NEW.ESTADO_ENTREGADO);
    END;
-- SELECT  * FROM HISTORIAL_ALQUILERES;